# ...
set_requestfile_path(ALIOG, "aliogApp/Db")
#set_requestfile_path("/home/epics/support.3.14.12.3/exphi-1.4.0/src")
file "/home/epics/support.3.14.12.3/exphi-1.4.0/src/exphi_settings.req",           P=14IDB:, E=Exphi
#
# ...
